export interface PublicError {
  code:
    | 'VALIDATION_ERROR'
    | 'CUSTOMER_NOT_FOUND'
    | 'CUSTOMER_TAX_ID_ALREADY_EXISTS'
    | 'DATABASE_ERROR'
    | 'INTERNAL_ERROR'
    | 'UNEXPECTED_ERROR'
    | 'BACKUP_CREATE_FAILED'
    | 'BACKUP_RESTORE_FAILED'
    | 'BACKUP_INVALID_FILE'
    | 'BACKUP_INCOMPATIBLE_VERSION'
    | 'BACKUP_OPERATION_IN_PROGRESS'
    | 'BACKUP_CANCELLED'
    | 'SYNC_NETWORK_UNAVAILABLE'
    | 'SYNC_AUTH_ERROR'
    | 'SYNC_REMOTE_ERROR'
    | 'SYNC_VALIDATION_ERROR'
    | 'SYNC_DUPLICATE_TAX_ID'
    | 'SYNC_OPERATION_IN_PROGRESS'
    | 'SYNC_DISABLED'
    | 'SYNC_CONFIGURATION_ERROR'
    | 'SYNC_CONFLICT'
    | 'SYNC_CONFLICT_NOT_FOUND'
    | 'SYNC_PULL_DISABLED';
  message: string;
  details?: unknown;
}
