export interface PublicError {
  code:
    | 'VALIDATION_ERROR'
    | 'CUSTOMER_NOT_FOUND'
    | 'CUSTOMER_TAX_ID_ALREADY_EXISTS'
    | 'DATABASE_ERROR'
    | 'INTERNAL_ERROR'
    | 'UNEXPECTED_ERROR'
    | 'BACKUP_CREATE_FAILED'
    | 'BACKUP_RESTORE_FAILED'
    | 'BACKUP_INVALID_FILE'
    | 'BACKUP_INCOMPATIBLE_VERSION'
    | 'BACKUP_OPERATION_IN_PROGRESS'
    | 'BACKUP_CANCELLED';
  message: string;
  details?: unknown;
}
